### ISSUE TITLE
Category static list shouldn't be in Category

### ISSUE THREAD

**Issue by MobileOak** [codeMagic23/DrillDownDocs#1]
https://github.com/codeMagic23/DrillDownDocs/blob/master/app/src/main/java/model/Category.java#L16

This shouldn't belong to the class and seems like a "global variable" (which is generally bad). The list should be owned by MainActivity or the SubcategoryActivity.

**Comment by codeMagic23** [comment]
Holding off on this as I'm still not sure of the best way to do this.
Need to add categories to the list and access attributes for each cat in the list
Static makes sense as there will only ever be one instance of each list

**Comment by codeMagic23** [comment]
Made as a member variable. 
Initialize in NetworkRequest class in the response function
JSON parsing function maybe should be moved to category class constructor or other function?
