### ISSUE TITLE
NetworkResponse interface

### ISSUE THREAD

**Issue by MobileOak** [codeMagic23/DrillDownDocs#10]
`updateList()` is a terrible name for a function that indicates "a network call happened and we got data back"

You should name it something like `onNetworkResponseSuccess` and you should have a separate function to handle `onNetworkResponseError`

You might even have a `onNetworkResponseLoading` or `onNetworkResponsePending` where you put up a loading indicator.

**Comment by codeMagic23** [comment]
Updated name to make sense
The error response function and loader make sense but I think this is fine for this project unless I get bored.
