### ISSUE TITLE
Need clearer comments on your example JSON blob

### ISSUE THREAD

**Issue by MobileOak** [codeMagic23/DrillDownDocs#14]
You have a sample response JSON in the comments in Category.java, and it makes no sense to me what in that JSON is a Category or Subcategory or what. Category.java line 50 - is this a Category object called "menu" ? what about "bottom menu" on line 55? If they're not Categories, why are you listing them in the comment? Or why not just comment in the JSON what's a category and what isn't?

**Comment by codeMagic23** [comment]
These example comments were just for me to understand their APIs as I go
Plan on removing the comments after completed as these should probably be in a readme
