### ISSUE TITLE
Implement GSON parsing for your Category objects

### ISSUE THREAD

**Issue by MobileOak** [codeMagic23/DrillDownDocs#15]
You shouldn't be rolling your own JSON parsing. Annotate all of your Category's member variables with the JSON key:

`@SerializedName("name")
String name;`

And then in your Request object, call this:
`Gson gson = new Gson();
Category category = gson.fromJson(jsonObject, Category.class);
`

**Comment by codeMagic23** [comment]
This would make sense for a production app but not sure it's too important for an interview test for a different framework and language.
Feel free to correct me if you feel differently.
